- README.md
- cluster_experiments/__init__.py
- cluster_experiments/power_analysis.py
- cluster_experiments/power_config.py
- cluster_experiments/random_splitter.py
- docs/index.md
- examples/cupac_example_gbm.py
- examples/cupac_example_target_mean.py
- examples/long_example.py
- examples/short_example.py
- examples/short_example_config.py
- examples/short_example_dict.py
- setup.py
- tests/test_power_analysis.py
- tests/test_splitter.py
This has breaking changes, will be released in 0.2.0
> refactor splitter

- cluster_experiments/__init__.py
- cluster_experiments/experiment_analysis.py
- cluster_experiments/power_config.py
- setup.py
- tests/test_analysis.py
- tests/test_splitter.py
- tests/utils.py
* Add from_config version of stratified
* Add t-test for analysis
* Add ols clustered for analysis
> add ttest and ols

- cluster_experiments/experiment_analysis.py
- cluster_experiments/power_analysis.py
- setup.py
* Use python engine
* OLS corrections
> Release 028

- setup.py
> release 031

- .github/workflows/testing.yml
- .pre-commit-config.yaml
- README.md
- cluster_experiments/__init__.py
- cluster_experiments/experiment_analysis.py
- cluster_experiments/power_analysis.py
- cluster_experiments/power_config.py
- docs/paired_ttest.ipynb
- examples/short_example_paired_ttest.py
- mkdocs.yml
- setup.py
- tests/analysis/test_analysis.py
- tests/examples.py
- tests/power_analysis/test_power_analysis.py
- tests/test_docs.py
Implement paired t test, based on ttest_rel (scipy.stats).
Strata is the column that will decide the comparison and the columns are generated from treatment_col. 
Minor comment:
In test_analysis.test_paired_ttest I am generating some fake data because it's specific to this test. If relevant I can pass it to a generic function so it's reusable.
> implement paired t test

- .flake8
- .pre-commit-config.yaml
- Makefile
- cluster_experiments/random_splitter.py
- examples/cupac_example_gbm.py
- examples/cupac_example_target_mean.py
- examples/long_example.py
- examples/short_example.py
- examples/short_example_config.py
- examples/short_example_dict.py
- ruff.toml
- setup.py
- tests/analysis/test_ols_analysis.py
- tests/cupac/test_aggregator.py
- tests/utils.py
> Use ruff as linter

- cluster_experiments/experiment_analysis.py
- setup.py
- tests/power_analysis/test_power_analysis.py
For both clustered and non-clustered
> Add OLS point estimates

- cluster_experiments/random_splitter.py
- setup.py
- tests/splitter/conftest.py
Remove ambiguous = infer parameter
> Remove ambiguous

- cluster_experiments/perturbator.py
- setup.py
- tests/perturbator/test_perturbator.py
Check that outcome is indeed binary, and average effect is in (-1, 1)
> Binary perturbator checks

- README.md
- cluster_experiments/power_analysis.py
- cluster_experiments/power_config.py
- setup.py
- tests/examples.py
- tests/power_analysis/conftest.py
- tests/power_analysis/test_seed.py
- tests/power_analysis/test_switchback_power.py
In this PR, I add the possibility to set a seed, so that simulations are reproducible. Also it will allow to make more fair comparisons betweens methods of analysis.
The main sources of stochasticity that are controlled with the seed are:
1. The splitter
2. The binary perturbator
> feat: add seed to reproduce simulations

- README.md
> feat: add versions in pypi

- .github/workflows/release.yml
- .github/workflows/testing.yml
- Makefile
> feat: add auto release

- cluster_experiments/power_config.py
Docs where failing to build as a future version of python was needed.
> fix: type hint config

- cluster_experiments/washover.py
> fix: improve formatting

- cluster_experiments/random_splitter.py
- setup.py
- tests/power_analysis/test_multivariate.py
- tests/power_analysis/test_seed.py
- tests/splitter/test_switchback_splitter.py
Addresses https://github.com/david26694/cluster-experiments/issues/145
> raise when time col not in cluster cols

- .github/workflows/docs.yml
> fix lxml docs

- README.md
Change the readme to show what the library does today
> Refer to actual library usage in readme

- cluster_experiments/power_analysis.py
Reverts david26694/cluster-experiments#199
Now I think I need you to approve @Gabrielcidral1 :)
> Revert "docs: add todo comment"

- .github/workflows/docs.yml
- .github/workflows/periodic.yml
- .github/workflows/release.yml
- setup.py
First step to deprecate 3.8 from lib
> drop py 3.8 from CI

- cluster_experiments/experiment_analysis.py
> refactor clustered ols

- cluster_experiments/experiment_analysis.py
- cluster_experiments/power_config.py
- pyproject.toml
- tests/analysis/conftest.py
- tests/analysis/test_formula.py
- tests/analysis/test_ols_analysis.py
- tests/power_config/test_params_flow.py
Adds possibility to create interaction covariates in regression methods
> add covariate interaction

- cluster_experiments/experiment_analysis.py
- tests/analysis/test_analysis.py
Added inference possibilities to Delta Method as well as confidence interval estimation.
Followed format from the other examples.
> feat: add inference delta method
